name: CI
'on':
  push:
  pull_request:
  workflow_dispatch:
env:
  FOUNDRY_PROFILE: ci
jobs:
  check:
    strategy:
      fail-fast: true
    name: Foundry project
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Show Forge version
        run: |
          forge --version
      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt
      - name: Run Forge build
        run: |
          forge build --sizes
        id: build
      - name: Run Forge Tests
        run: |
          forge test -vvvv
        id: test
      - name: Run Slither
        uses: crytic/slither-action@v0.4.0
        id: slither
        with:
          sarif: results.sarif
          fail-on: none
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
          category: slither
